# Generated by Django 3.1 on 2020-08-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200815_1516'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
