# Generated by Django 3.1 on 2020-08-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
