# Generated by Django 3.1 on 2020-08-31 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200830_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='opened',
            field=models.DateField(default=datetime.date(2020, 8, 31)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateField(default=datetime.date(2020, 8, 31)),
        ),
    ]
