# Generated by Django 3.1 on 2020-08-31 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200831_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='upvote',
            new_name='votes',
        ),
        migrations.AddField(
            model_name='thread',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='main.thread'),
        ),
    ]
