# Generated by Django 3.1 on 2020-08-31 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200831_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='main.thread'),
        ),
    ]
