# Generated by Django 3.1 on 2020-08-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_employee_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
