# Generated by Django 3.1 on 2020-12-20 04:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_issue_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='project',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='source',
        ),
        migrations.AddField(
            model_name='issue',
            name='comment',
            field=models.CharField(default=str, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='main.issue'),
        ),
        migrations.AddField(
            model_name='project',
            name='issues',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, to='main.issue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='opened',
            field=models.DateField(default=datetime.date(2020, 12, 20)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateField(default=datetime.date(2020, 12, 20)),
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
