# Generated by Django 3.1 on 2020-12-20 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201220_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='role',
        ),
    ]
