# Generated by Django 3.1 on 2020-12-20 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_projectmember_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='issues',
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, to='main.project'),
            preserve_default=False,
        ),
    ]
