# Generated by Django 3.1 on 2020-12-20 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_project_project_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_manager',
        ),
    ]
