# Generated by Django 3.1 on 2020-08-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
