# Generated by Django 3.1 on 2020-12-20 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0014_project_project_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='role',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, to='auth.group', to_field='name'),
            preserve_default=False,
        ),
    ]
