# Generated by Django 3.1 on 2020-12-29 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_projectmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='desc',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='issue',
            name='opened',
            field=models.DateField(default=datetime.date(2020, 12, 29)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateField(default=datetime.date(2020, 12, 29)),
        ),
    ]
