# Generated by Django 3.1 on 2021-01-09 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201229_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='opened',
            field=models.DateField(default=datetime.date(2021, 1, 9)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateField(default=datetime.date(2021, 1, 9)),
        ),
    ]
