# Generated by Django 3.1 on 2020-08-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200826_1007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
