# Generated by Django 3.1 on 2020-08-26 10:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_issue_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateField(default=datetime.datetime(2020, 8, 26, 10, 45, 10, 489652, tzinfo=utc)),
        ),
    ]
