# Generated by Django 3.1 on 2020-08-26 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200826_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='name',
            new_name='title',
        ),
    ]
