# Generated by Django 3.1 on 2020-08-26 11:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0023_auto_20200826_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=250)),
                ('start', models.DateField(default=datetime.date(2020, 8, 26))),
                ('end', models.DateField(blank=True, null=True)),
                ('issues_open', models.IntegerField(default=0)),
                ('total_issues', models.IntegerField(default=0)),
                ('issues_closed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('priority', models.CharField(max_length=30)),
                ('proj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
    ]
