# Generated by Django 3.1 on 2020-08-26 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_issue_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project'),
        ),
    ]
